#! /usr/bin/env python3
"""System monitoring daemon."""

from logging import INFO, basicConfig

from sysmon import run_checks
from sysmon.config import LOGGER, LOG_FORMAT


def main():
    """Runs the daemon."""

    basicConfig(level=INFO, format=LOG_FORMAT)

    try:
        run_checks()
    except KeyboardInterrupt:
        LOGGER.error('Aborted by user.')
        return 1


if __name__ == '__main__':
    main()
