#! /usr/bin/env python3
"""System monitoring daemon."""

from logging import INFO, basicConfig

from sysmon import run_checks
from sysmon.config import LOG_FORMAT


def main():
    """Runs the daemon."""

    basicConfig(level=INFO, format=LOG_FORMAT)

    try:
        while True:
            run_checks()
    except KeyboardInterrupt:
        return


if __name__ == '__main__':
    main()
